export * from './home/home.component'
export * from './list/list.component'
export * from './list-item/list-item.component'
export * from './about/about-company/about-company.component'
export * from './about/about.component'
